universe = vanilla
log    =    log/final_project_$(Cluster)_$(Process).log
error  =  error/final_project_$(Cluster)_$(Process).err
output = output/final_project_$(Cluster)_$(Process).out

executable = ./main.sh
arguments = $(Process)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = R413.tar.gz, main.R, packages.tar.gz, NRC-Lexicon.txt

request_cpus = 1
request_memory = 1GB
request_disk = 3GB

queue 3000