universe = vanilla
log    =    log/final_project_$(Cluster)_$(Process).log
error  =  error/final_project_$(Cluster)_$(Process).err
output = output/final_project_$(Cluster)_$(Process).out

executable = ./main.sh
arguments = $(Process)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/el8/R413.tar.gz

request_cpus = 1
request_memory = 100MB
request_disk = 100MB

queue 500